/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class L01_HelloWorld */

#ifndef _Included_L01_HelloWorld
#define _Included_L01_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     L01_HelloWorld
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_L01_1HelloWorld_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
