/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bvolpato_query_jni_L01_HelloWorld */

#ifndef _Included_org_bvolpato_query_jni_L01_HelloWorld
#define _Included_org_bvolpato_query_jni_L01_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bvolpato_query_jni_L01_HelloWorld
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_bvolpato_query_jni_L01_1HelloWorld_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
