/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.brunovolpato.calcite.learn;

import java.sql.*;
import org.apache.calcite.jdbc.CalciteConnection;
import org.apache.calcite.plan.RelOptUtil;
import org.apache.calcite.plan.hep.HepPlanner;
import org.apache.calcite.plan.hep.HepProgram;
import org.apache.calcite.plan.hep.HepProgramBuilder;
import org.apache.calcite.rel.RelNode;
import org.apache.calcite.rel.rules.CoreRules;
import org.apache.calcite.rel.type.RelDataTypeSystem;
import org.apache.calcite.schema.SchemaPlus;
import org.apache.calcite.sql.SqlNode;
import org.apache.calcite.sql.parser.SqlParseException;
import org.apache.calcite.sql2rel.RelFieldTrimmer;
import org.apache.calcite.tools.*;

public class L07_CalciteSQLOptimizer {

  public static void main(String[] args)
      throws SQLException,
          ClassNotFoundException,
          SqlParseException,
          RelConversionException,
          ValidationException {
    Class.forName("org.apache.calcite.jdbc.Driver");

    // Create a connection to Calcite using the model
    Connection connection =
        DriverManager.getConnection(
            "jdbc:calcite:model=" + L04_RelBuilder.class.getResource("/model.json").getFile());
    CalciteConnection calciteConnection = connection.unwrap(CalciteConnection.class);
    SchemaPlus rootSchema = calciteConnection.getRootSchema();

    FrameworkConfig frameworkConfig =
        Frameworks.newConfigBuilder()
            .defaultSchema(rootSchema.getSubSchema("schema"))
            .typeSystem(RelDataTypeSystem.DEFAULT)
            .build();
    RelBuilder builder = RelBuilder.create(frameworkConfig);

    String sql =
        "SELECT p.\"first_name\", s.\"salary\" FROM \"Person\" p LEFT JOIN \"Salary\" s ON p.\"position\" = s.\"position\" WHERE \"age\" > 30";

    {
      Planner planner = Frameworks.getPlanner(frameworkConfig);

      SqlNode parsed = planner.validate(planner.parse(sql));
      RelNode relNode = planner.rel(parsed).project();
      System.out.println("Plan: " + RelOptUtil.toString(relNode));

      final HepProgram hepProgram =
          new HepProgramBuilder()
              .addRuleInstance(CoreRules.FILTER_INTO_JOIN)
              .addRuleInstance(CoreRules.PROJECT_TO_CALC)
              .addRuleInstance(CoreRules.JOIN_CONDITION_PUSH)
              .addRuleInstance(CoreRules.PROJECT_JOIN_TRANSPOSE)
              .addRuleInstance(CoreRules.SORT_REMOVE)
              .build();

      final HepPlanner hepPlanner = new HepPlanner(hepProgram);
      hepPlanner.setRoot(relNode);
      final RelNode relNodeBest = hepPlanner.findBestExp();
      final RelFieldTrimmer fieldTrimmer = new RelFieldTrimmer(null, builder);
      final RelNode trimmed = fieldTrimmer.trim(relNodeBest);
      System.out.println("Trimmed: " + RelOptUtil.toString(trimmed));
    }

    //    {
    //      Planner planner = Frameworks.getPlanner(frameworkConfig);
    //
    //      final VolcanoPlanner volcanoPlanner = new VolcanoPlanner();
    //
    //      SqlNode parsedPlan = planner.parse(sql);
    //      SqlNode parsed = planner.validate(parsedPlan);
    //      RelNode relNode = planner.rel(parsed).project();
    //      System.out.println("Plan b4: " + RelOptUtil.toString(relNode));
    //
    ////      RelOptCluster cluster = RelOptCluster.create(volcanoPlanner, );
    ////      relNode = relNode.copy(relNode.getTraitSet(), List.of(relNode));
    //      volcanoPlanner.setRoot(relNode);
    //
    //      final RelNode relNodeBest = volcanoPlanner.findBestExp();
    //      final RelFieldTrimmer fieldTrimmer = new RelFieldTrimmer(null, builder);
    //      final RelNode trimmed = fieldTrimmer.trim(relNodeBest);
    //      System.out.println("Volcano: " + RelOptUtil.toString(trimmed));
    //    }

    // Close the connection when done
    connection.close();
  }
}
